import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Provider from "@/SessionProvider";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#020202] text-white`}>
        <Provider>
          <Navbar />
          <ToastContainer position="bottom-right" />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
